GET https://mbehymer341test.onrender.com/ HTTP/1.1

###
GET https://mbehymer341test.onrender.com/parents HTTP/1.1

###
GET https://mbehymer341test.onrender.com/ HTTP/1.1

### Local Host

###
GET http://localhost:8080/ HTTP/1.1
###
POST http://localhost:8080/contacts
Content-Type: application/json

{
    "birthday": "99/99/9999",
    "email": "test.test@gmail.com",
    "favoriteColor": "testcolor",
    "firstName": "John",
    "lastName": "Doe"
}

###
PUT http://localhost:8080/contacts/63d476e2229c2d6bd9e427f2
Content-Type: application/json

{
    "birthday": "99/99/9999",
    "email": "john.doe@gmail.com",
    "favoriteColor": "green",
    "firstName": "John",
    "lastName": "Doe"
}


###
DELETE http://localhost:8080/



### RENDER
POST https://mbehymer341test.onrender.com/contacts
Content-Type: application/json

{
    "_id": "1234567890",
    "birthday": "11/05/1949",
    "email": "jerry.bingham@gmail.com",
    "favoriteColor": "red",
    "firstName": "Jerry",
    "lastName": "Bingham"
}

###
PUT https://mbehymer341test.onrender.com/contacts?_id=1234567890
Content-Type: application/json

{
    "birthday": "11/05/1949",
    "email": "jerry.bingham@gmail.com",
    "favoriteColor": "green",
    "firstName": "Jerry",
    "lastName": "Bingham"
}


###
DELETE https://mbehymer341test.onrender.com/contacts?_id=1234567890