GET https://mbehymer341test.onrender.com/ HTTP/1.1

###
GET https://mbehymer341test.onrender.com/parents HTTP/1.1

###
GET https://mbehymer341test.onrender.com/ HTTP/1.1

### Local Host

###
GET http://localhost:8080/ HTTP/1.1
###
GET http://localhost:8080/contacts/63d4788657e4d5ab7c5c5e57 HTTP/1.1
###
POST http://localhost:8080/contacts
Content-Type: application/json

{
    "birthday": "99/99/9999",
    "email": "test.test@gmail.com",
    "favoriteColor": "testcolor",
    "firstName": "John",
    "lastName": "Doe"
}

###
PUT http://localhost:8080/contacts/63d4788657e4d5ab7c5c5e57
Content-Type: application/json

{
    "birthday": "99/99/9999",
    "email": "john.doe@gmail.com",
    "favoriteColor": "green",
    "firstName": "John",
    "lastName": "Doe"
}


###
DELETE http://localhost:8080/contacts/63d4788657e4d5ab7c5c5e57



### RENDER
POST https://mbehymer341test.onrender.com/contacts
Content-Type: application/json

{
    "birthday": "99/99/9999",
    "email": "test.test@gmail.com",
    "favoriteColor": "testcolor",
    "firstName": "John",
    "lastName": "Doe"
}

###
GET http://mbehymer341test.onrender.com/contacts/63d47e97d937cdb31b05e6fd HTTP/1.1

###
PUT https://mbehymer341test.onrender.com/contacts/63d47e97d937cdb31b05e6fd
Content-Type: application/json

{
    "birthday": "99/99/9999",
    "email": "john.doe@gmail.com",
    "favoriteColor": "green",
    "firstName": "John",
    "lastName": "Doe"
}



###
DELETE https://mbehymer341test.onrender.com/contacts/63d47e97d937cdb31b05e6fd